- name: redis setup
  hosts: all
  become: yes
  tasks:
    - name: Install a package
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: true
    - name: enable redis module
      ansible.builtin.shell: yum enable redis:remi-6.2 -y
    - name: Install redis
      ansible.builtin.yum:
        name: redis
        state: started
    - name: Update listen address in mongodb configuration
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: Update listen address in mongodb configuration
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: start redis
      ansible.builtin.systemd:
        name: redis
        state: restarted
        enabled: yes

#   systemctl enable redis
#   systemctl restart redis